"""Write visualizer/data.js: everything the visualizer shows, in one JS file.

Usage: python tools/bundle.py

data.js is loaded with <script src> because fetch() does not work on file:// pages.
Layout values the engine gets from codegen (dialog word-wrap, menu positions) are
included under "derived" so the visualizer draws exactly what the GBA draws.
"""
import datetime
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C  # noqa: E402
import validate  # noqa: E402


def derived(p):
    out = {"dialogs": {}, "menus": {}}
    for nid, n in p.nodes.items():
        t = p.type_of(nid)
        try:
            if t == "dialog" and isinstance(n.get("box"), dict):
                lines = []
                for ln in n.get("lines", []):
                    lay = C.dialog_layout(n["box"], ln)
                    wrapped, _ = C.wrap_text(ln.get("text", ""), max(1, lay["text_w"]))
                    lay["wrapped"] = wrapped
                    lines.append(lay)
                choice = C.dialog_layout(n["box"], {})
                out["dialogs"][nid] = {"lines": lines, "choices": [
                    [choice["inner_x"] + 1, choice["inner_y"] + i] for i in range(len(n.get("choices") or []))]}
            elif t == "menu":
                out["menus"][nid] = C.menu_layout(n)
        except (KeyError, TypeError, ValueError):
            pass
    return out


def bundle(p=None, report=None):
    """Write visualizer/data.js. Returns its path."""
    p = p or C.load_project()
    r = report or validate.validate(p)
    data = {
        "generated_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "game": p.game,
        "index": p.index,
        "nodes": p.nodes,
        "catalog": {"behaviors": p.behaviors, "actions": p.actions},
        "validation": {"ok": r.ok, "errors": r.errors, "warnings": r.warnings},
        "engine": {
            "limits": C.read_engine_limits(),
            "anim_slots": C.ANIM_SLOTS,
            "sound_events": C.SOUND_EVENTS,
            "categories": C.CATEGORIES,
            "scene_types": C.SCENE_TYPES,
            "object_types": {t: {"prefix": v[0], "owns": v[1]} for t, v in C.OBJECT_TYPES.items()},
            "gravity": p.game.get("gravity", 0.25),
            "max_fall_speed": p.game.get("max_fall_speed", 4),
        },
        "derived": derived(p),
    }
    os.makedirs(C.VIS_DIR, exist_ok=True)
    path = os.path.join(C.VIS_DIR, "data.js")
    text = "// GENERATED by tools/bundle.py - do not edit.\nwindow.GAME_DATA = %s;\n" % json.dumps(
        data, ensure_ascii=True, separators=(",", ":"))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return path


def main():
    C.setup_console()
    p = C.load_project()
    r = validate.validate(p)
    bundle(p, r)
    state = "ok" if r.ok else "%d validation error(s) - the visualizer lists them" % len(r.errors)
    print("✔ visualizer/data.js updated (%d nodes, %s)." % (len(p.nodes), state))
    return 0


if __name__ == "__main__":
    sys.exit(main())
