"""Turn the nodes into const C data (lives in ROM) under generated/.

Usage: python tools/codegen.py

Writes:
  generated/node_ids.h          NODE_*, VAR_*, BHV_*, ACT_*, ... enums
  generated/behavior_params.h   one params struct per behavior (from catalog/behaviors.json)
  generated/game_data.h / .c    every node as const data (layout = src/engine/data.h)
  generated/behaviors_table.c   behavior function table + custom code hooks

This file is one of the "four mirrors" (CLAUDE.md rule 8): each node type has an
emit function here (E_<type>) matching the struct in src/engine/data.h.
Only files whose content changed are rewritten, so builds stay incremental.
"""
import math
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C  # noqa: E402

HEADER = "// GENERATED by tools/codegen.py from nodes/ - do not edit. Change the nodes instead.\n"


def up(s):
    return re.sub(r"[^A-Za-z0-9]", "_", s).upper()


def fx(v):
    """Number -> 24.8 fixed-point int."""
    return int(round(float(v) * 256))


def cstr(s):
    """C string literal; everything outside plain ASCII letters/digits/space is octal-escaped."""
    if s is None:
        return "NULL"
    out = []
    for ch in s:
        o = ord(ch)
        if ch.isalnum() and o < 128 or ch in " .,:;!-+=()/'*#%&@[]_<>^~|$":
            out.append(ch)
        else:
            out.append("\\%03o" % (o & 0xFF))
    return '"' + "".join(out) + '"'


def tile_words(rows, ox=0, oy=0):
    """Encode one 8x8 block (top-left at ox, oy) as 8 u32 words, 4 bits per pixel."""
    words = []
    for y in range(8):
        w = 0
        row = rows[oy + y]
        for x in range(8):
            w |= C.pixel_index(row[ox + x]) << (4 * x)
        words.append(w)
    return words


def image_tiles(rows):
    """Encode a whole image as 8x8 tiles in row-major order (GBA 1D mapping)."""
    h, w = len(rows), len(rows[0])
    out = []
    for ty in range(h // 8):
        for tx in range(w // 8):
            out.extend(tile_words(rows, tx * 8, ty * 8))
    return out


def u32_array(words, per_line=8):
    lines = []
    for i in range(0, len(words), per_line):
        lines.append("    " + ", ".join("0x%08X" % w for w in words[i:i + per_line]) + ",")
    return "\n".join(lines) if lines else "    0"


def int_array(vals, per_line=24):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(str(v) for v in vals[i:i + per_line]) + ",")
    return "\n".join(lines) if lines else "    0"


class Gen:
    def __init__(self, p):
        self.p = p
        self.ids = [e["id"] for e in p.index]
        self.vars = p.var_names()
        self.out = []
        self.n = 0
        self.extern_fns = set()          # prototypes for custom code

    # ---- small helpers ----
    def sym(self, base):
        self.n += 1
        return "%s_%d" % (re.sub(r"\W", "_", base), self.n)

    def emit(self, text):
        self.out.append(text)

    def node_enum(self, nid):
        return "NODE_%s" % up(nid) if nid else "-1"

    def var_enum(self, name):
        return "VAR_%s" % up(name) if name else "-1"

    def ptr(self, nid):
        return "&node_%s" % nid if nid else "NULL"

    # ---- action lists ----
    def actions(self, lst, base):
        """Emit an Action array; return an ActionList initializer."""
        if not lst:
            return "{ NULL, 0 }"
        items = []
        for a in lst:
            items.append(self.action(a, base))
        s = self.sym(base + "_act")
        self.emit("static const Action %s[] = {\n%s\n};" % (s, ",\n".join("    " + i for i in items)))
        return "{ %s, %d }" % (s, len(lst))

    def action(self, a, base):
        do = a["do"]
        spec = self.p.actions[do]["params"]

        def val(k):
            if k in a:
                return a[k]
            return spec.get(k, {}).get("default")

        op = "ACT_%s" % up(do)
        sub, node, var, va, vb = 0, "-1", "-1", 0, 0
        var_from = var_max = "-1"
        then_l = else_l = "{ NULL, 0 }"
        fn = "NULL"
        if do == "goto_scene":
            node = self.node_enum(val("scene"))
        elif do in ("fade_in", "fade_out", "wait"):
            va = int(val("ticks") or 0)
        elif do == "play_sfx":
            node = self.node_enum(val("sfx"))
        elif do == "play_music":
            node = self.node_enum(val("music"))
        elif do in ("set_var", "add_var"):
            var, va = self.var_enum(val("var")), int(val("value") or 0)
            var_from = self.var_enum(val("from"))
            if do == "add_var":
                var_max = self.var_enum(val("max_var"))
        elif do == "if_chance":
            va = int(val("percent"))
            then_l = self.actions(val("then") or [], base + "_then")
            else_l = self.actions(val("else") or [], base + "_else")
        elif do == "if_var":
            ops = spec["op"]["options"]
            var, va, sub = self.var_enum(val("var")), int(val("value")), ops.index(val("op"))
            then_l = self.actions(val("then") or [], base + "_then")
            else_l = self.actions(val("else") or [], base + "_else")
        elif do == "show_dialog":
            node = self.node_enum(val("dialog"))
        elif do == "open_menu":
            node = self.node_enum(val("menu"))
        elif do == "spawn":
            node = self.node_enum(val("object"))
            va, vb, sub = int(val("x") or 0), int(val("y") or 0), 1 if val("relative") else 0
        elif do == "shake_camera":
            va, vb = int(val("ticks") or 0), int(val("strength") or 0)
        elif do == "call":
            fn = val("function")
            self.extern_fns.add("void %s(struct Actor *self);" % fn)
        return ("{ %s, %d, %s, %s, %s, %s, 0, %d, %d, %s, %s, %s }"
                % (op, sub, node, var, var_from, var_max, va, vb, then_l, else_l, fn))

    def text(self, t):
        """C string for UI text: {var} -> \\001 + (var+1), {var:02} -> \\002 + (var+1)."""
        if t is None:
            return "NULL"
        t = C.PLACEHOLDER_RE.sub(
            lambda m: ("\x02" if m.group(2) else "\x01") + chr(self.vars.index(m.group(1)) + 1), t)
        return cstr(t)

    # ---- behavior params ----
    def param_init(self, ptype, pdef, v, base):
        if ptype in ("int", "ticks"):
            return str(int(v))
        if ptype == "fixed":
            return str(fx(v))
        if ptype == "bool":
            return "1" if v else "0"
        if ptype == "button":
            return "0x%03X" % C.BUTTONS[v]
        if ptype == "var":
            return self.var_enum(v)
        if ptype == "choice":
            return str(pdef["options"].index(v))
        if ptype == "string":
            return cstr(v)
        if ptype == "actions":
            return self.actions(v or [], base)
        if ptype == "points":
            s = self.sym(base + "_pts")
            flat = [c for pt in v for c in pt]
            self.emit("static const s16 %s[] = { %s };" % (s, ", ".join(str(c) for c in flat)))
            return "{ %s, %d }" % (s, len(v))
        if ptype.startswith("node:"):
            t = ptype[5:]
            if t in PARAM_NODE_PTR:
                return self.ptr(v)
            return self.node_enum(v)
        raise ValueError(ptype)

    def logic(self, entries, base, overrides=None, name=None):
        """Emit params + a LogicEntry array; return (symbol, count). `name` = public symbol."""
        if not entries:
            return "NULL", 0
        overrides = overrides or {}
        items = []
        for e in entries:
            b = e["behavior"]
            spec = self.p.behaviors[b].get("params", {})
            given = dict(e.get("params") or {})
            given.update(overrides.get(b, {}))
            fields = []
            for pname, pdef in spec.items():
                v = given.get(pname, pdef.get("default"))
                fields.append(".%s = %s" % (pname, self.param_init(pdef["type"], pdef, v, "%s_%s" % (base, b))))
            ps = self.sym("prm_%s_%s" % (base, b))
            body = ", ".join(fields) if fields else ".unused = 0"
            self.emit("static const Params_%s %s = { %s };" % (b, ps, body))
            items.append("{ BHV_%s, &%s }" % (up(b), ps))
        if name:
            s = name
            self.emit("const LogicEntry %s[] = { %s };" % (s, ", ".join(items)))
        else:
            s = self.sym("logic_" + base)
            self.emit("static const LogicEntry %s[] = { %s };" % (s, ", ".join(items)))
        return s, len(entries)

    # ---- per-type emitters ----
    def E_palette(self, nid, n):
        cols = [C.color_to_bgr555(c) for c in n["colors"]]
        self.emit("const PaletteData node_%s = { %d, { %s } };" % (
            nid, len(cols), ", ".join("0x%04X" % c for c in cols)))

    def E_sprite(self, nid, n):
        w, h = n["width"], n["height"]
        shape, size = C.OBJ_SIZES[(w, h)]
        words = []
        for rows in n["frames"].values():
            words.extend(image_tiles(rows))
        s = self.sym(nid + "_tiles")
        self.emit("static const u32 %s[] = {\n%s\n};" % (s, u32_array(words)))
        self.emit("const SpriteData node_%s = { %s, %d, %d, %d, %d, %d, %d, %s };" % (
            nid, self.ptr(n["palette"]), w, h, shape, size, (w // 8) * (h // 8), len(n["frames"]), s))

    def E_tileset(self, nid, n):
        words = [0] * 8
        flags = [0]
        for t in n["tiles"].values():
            words.extend(tile_words(t["pixels"]))
            f = 0
            for bit, name in enumerate(C.TILE_FLAGS):
                if t.get(name):
                    f |= 1 << bit
            flags.append(f)
        ts, fs = self.sym(nid + "_tiles"), self.sym(nid + "_flags")
        self.emit("static const u32 %s[] = {\n%s\n};" % (ts, u32_array(words)))
        self.emit("static const u8 %s[] = { %s };" % (fs, ", ".join(str(f) for f in flags)))
        self.emit("const TilesetData node_%s = { %s, %d, %s, %s };" % (
            nid, self.ptr(n["palette"]), len(flags), ts, fs))

    def E_tilemap(self, nid, n):
        tiles = list(self.p.nodes[n["tileset"]]["tiles"].keys())
        index = {ch: i + 1 for i, ch in enumerate(tiles)}
        cells = [index.get(ch, 0) for row in n["rows"] for ch in row]
        s = self.sym(nid + "_cells")
        self.emit("static const u8 %s[] = {\n%s\n};" % (s, int_array(cells, 32)))
        self.emit("const TilemapData node_%s = { %s, %d, %d, %d, %d, %d, %s };" % (
            nid, self.ptr(n["tileset"]), n["layer"], 1 if n.get("repeat_x") else 0,
            fx(n.get("parallax", 1)), len(n["rows"][0]), len(n["rows"]), s))

    def E_font(self, nid, n):
        glyphs = list(n["glyphs"].items())
        words = []
        index = {}
        for i, (ch, rows) in enumerate(glyphs):
            words.extend(tile_words(rows))
            index[ch] = i + 1
        cmap = [0] * 128
        for code in range(32, 127):
            ch = chr(code)
            cmap[code] = index.get(ch, index.get(ch.upper(), 0))
        ts, ms = self.sym(nid + "_tiles"), self.sym(nid + "_map")
        self.emit("static const u32 %s[] = {\n%s\n};" % (ts, u32_array(words)))
        self.emit("static const u8 %s[128] = {\n%s\n};" % (ms, int_array(cmap, 32)))
        self.emit("const FontData node_%s = { %s, %d, %s, %s };" % (nid, self.ptr(n["palette"]), len(glyphs), ts, ms))

    def E_icon(self, nid, n):
        size = len(n["pixels"])
        s = self.sym(nid + "_tiles")
        self.emit("static const u32 %s[] = {\n%s\n};" % (s, u32_array(image_tiles(n["pixels"]))))
        self.emit("const IconData node_%s = { %s, %d, %d, %s };" % (nid, self.ptr(n["palette"]), size, size, s))

    def E_sfx(self, nid, n):
        ch = C.CHANNELS.index(n["channel"])
        steps = []
        for st in n["steps"]:
            if n["channel"] == "noise":
                v = int(st["pitch"])
            else:
                v = 0xFE if st["note"] == ".." else C.note_number(st["note"])
            vol = st.get("volume", 4 if n["channel"] == "wave" else 12)
            steps.append("{ %d, %d, %d, 0 }" % (v, st["ticks"], vol))
        s = self.sym(nid + "_steps")
        self.emit("static const SfxStep %s[] = { %s };" % (s, ", ".join(steps)))
        self.emit("const SfxData node_%s = { %d, %d, %d, %d, %s };" % (
            nid, ch, n.get("duty", 2), n.get("priority", 0), len(steps), s))

    def E_music(self, nid, n):
        rows = {ch: [] for ch in C.CHANNELS}
        used = {ch: False for ch in C.CHANNELS}
        for pname in n["order"]:
            pat = n["patterns"][pname]
            length = len(C.split_music_tokens(next(iter(pat.values()))))
            for ch in C.CHANNELS:
                if ch in pat:
                    used[ch] = True
                    for t in C.split_music_tokens(pat[ch]):
                        if t == "--":
                            rows[ch].append(0xFF)
                        elif t == "..":
                            rows[ch].append(0xFE)
                        elif ch == "noise":
                            rows[ch].append(int(t[1], 16))
                        else:
                            rows[ch].append(C.note_number(t))
                else:
                    rows[ch].extend([0xFE] * length)
        row_count = len(rows["square1"])
        ptrs, insts = [], []
        for ch in C.CHANNELS:
            ins = n.get("instruments", {}).get(ch)
            if used[ch]:
                s = self.sym("%s_%s" % (nid, ch))
                self.emit("static const u8 %s[] = {\n%s\n};" % (s, int_array(rows[ch], 32)))
                ptrs.append(s)
            else:
                ptrs.append("NULL")
            if ins:
                wave = [0, 0, 0, 0]
                if ch == "wave":
                    hx = ins["wave"]
                    bs = [int(hx[i:i + 2], 16) for i in range(0, 32, 2)]
                    wave = [bs[i] | bs[i + 1] << 8 | bs[i + 2] << 16 | bs[i + 3] << 24 for i in range(0, 16, 4)]
                vol = ins.get("volume", 4 if ch == "wave" else 10)
                insts.append("{ 1, %d, %d, %d, { 0x%08X, 0x%08X, 0x%08X, 0x%08X } }" % (
                    ins.get("duty", 2), vol, ins.get("decay", 0), *wave))
            else:
                insts.append("{ 0, 0, 0, 0, { 0, 0, 0, 0 } }")
        tpr = fx(3600.0 / (n["bpm"] * n["rows_per_beat"]))
        self.emit("const MusicData node_%s = { %d, %d, %d, { %s }, { %s } };" % (
            nid, tpr, 1 if n.get("loop", True) else 0, row_count, ", ".join(insts), ", ".join(ptrs)))

    def E_animation(self, nid, n):
        names = list(self.p.nodes[n["sprite"]]["frames"].keys())
        frames = []
        for f in n["frames"]:
            flip = (1 if f.get("flip_x") else 0) | (2 if f.get("flip_y") else 0)
            frames.append("{ %d, %d, %d }" % (names.index(f["frame"]), f["ticks"], flip))
        fs = self.sym(nid + "_frames")
        self.emit("static const AnimFrame %s[] = { %s };" % (fs, ", ".join(frames)))
        evs = n.get("events") or []
        es = "NULL"
        if evs:
            items = []
            for i, ev in enumerate(evs):
                lst = [ev["action"]] if "action" in ev else ev.get("actions", [])
                items.append("{ %d, %s }" % (ev["at"], self.actions(lst, "%s_ev%d" % (nid, i))))
            es = self.sym(nid + "_events")
            self.emit("static const AnimEvent %s[] = { %s };" % (es, ", ".join(items)))
        self.emit("const AnimationData node_%s = { %s, %d, %d, %d, 0, %s, %s };" % (
            nid, self.ptr(n["sprite"]), 1 if n.get("loop", True) else 0, len(frames), len(evs), fs, es))

    def E_particle(self, nid, n):
        sp, an = n["speed"], n["angle"]
        self.emit("const ParticleData node_%s = { %s, %s, %d, %d, %d, %d, %d, %d, %d, %d };" % (
            nid, self.ptr(n["animation"]), "PTC_BURST" if n["mode"] == "burst" else "PTC_STREAM",
            n.get("count", 1), n.get("rate", 1), n["lifetime"], fx(sp[0]), fx(sp[1]),
            fx(n.get("gravity", 0)), int(an[0]), int(an[1])))

    def E_body(self, nid, n):
        hb = n["hitbox"]
        ph = n.get("physics", {})
        mask = 0
        for cat in ph.get("collides_with", []):
            mask |= 1 << C.CATEGORIES.index(cat)
        anims = ", ".join(self.ptr(n["animations"].get(slot)) for slot in C.ANIM_SLOTS)
        self.emit("const BodyData node_%s = { %d, %d, %d, %d, %d, %d, %d, %d, 0x%X, ANIM_%s, { %s } };" % (
            nid, n["origin"][0], n["origin"][1], hb["x"], hb["y"], hb["w"], hb["h"],
            1 if ph.get("gravity") else 0, 1 if ph.get("solid") else 0, mask,
            up(n["default_animation"]), anims))

    def E_actor(self, nid, n):
        t = self.p.type_of(nid)
        lsym, lcount = self.logic(n.get("logic") or [], nid, name="logic_" + nid)
        snd = ", ".join(self.node_enum((n.get("sounds") or {}).get(ev)) for ev in C.SOUND_EVENTS)
        zone = n.get("zone", {})
        hooks = self.hooks(nid, n, "void %s(struct Actor *self);")
        self.emit("const ActorData node_%s = { NT_%s, CAT_%s, %s, %d, %d, %d, %s, { %s }, %s, %s };" % (
            nid, up(t), up(t), self.ptr(n.get("body")), zone.get("w", 0), zone.get("h", 0),
            lcount, lsym, snd, hooks[0], hooks[1]))

    def hooks(self, nid, n, proto):
        """Custom code: find <id>_on_start / <id>_on_update in src/game/<id>.c."""
        if not n.get("code"):
            return "NULL", "NULL"
        path = os.path.join(C.ROOT, n["code"])
        with open(path, "r", encoding="utf-8") as f:
            src = f.read()
        out = []
        for h in ("on_start", "on_update"):
            name = "%s_%s" % (nid, h)
            if re.search(r"\b%s\s*\(" % name, src):
                self.extern_fns.add(proto % name)
                out.append(name)
            else:
                out.append("NULL")
        return out

    def E_hud(self, nid, n):
        items = []
        for e in n["elements"]:
            kind = e["kind"]
            x, y = e["x"] // 8, e["y"] // 8
            text = "NULL"
            icon = self.ptr(e.get("icon"))
            empty = self.ptr(e.get("empty_icon"))
            var = self.var_enum(e.get("var"))
            mx = length = color = back = spacing = 0
            if kind == "text":
                text = self.text(e["text"])
            elif kind == "icon_repeat":
                size = len(self.p.nodes[e["icon"]]["pixels"])
                mx, spacing = e["max"], e.get("spacing", size) // 8
            elif kind == "bar":
                mx, length, color, back = e["max"], e["length"], e["color"], e.get("back", 0)
            items.append("{ HUD_%s, %d, %d, %d, %s, %d, %d, %d, %d, %s, %s, %s }" % (
                up(kind), x, y, mx, var, length, color, back, spacing, icon, empty, text))
        s = self.sym(nid + "_elements")
        self.emit("static const HudElement %s[] = {\n    %s\n};" % (s, ",\n    ".join(items)))
        self.emit("const HudData node_%s = { %s, %d, %s };" % (nid, self.ptr(n["font"]), len(items), s))

    def box(self, b):
        if not b:
            return "{ 0, 0, 0, 0, 0, 0 }"
        x, y, w, h = C.box_tiles(b)
        return "{ %d, %d, %d, %d, %d, %d }" % (x, y, w, h, b.get("paper", 1), b.get("border", 2))

    def options(self, opts, positions, base):
        items = []
        for i, (x, y) in enumerate(positions):
            o = opts[i] if i < len(opts) else {}            # upgrade menus: card slots only
            items.append("{ %s, %d, %d, %s }" % (self.text(o.get("label")), x, y, self.actions(o.get("actions") or [], "%s_opt%d" % (base, i))))
        s = self.sym(base + "_options")
        self.emit("static const MenuOption %s[] = {\n    %s\n};" % (s, ",\n    ".join(items)))
        return s

    def E_menu(self, nid, n):
        lay = C.menu_layout(n)
        opts = self.options(n.get("options") or [], lay["options"], nid)
        snd = n.get("sounds") or {}
        cancel = self.actions(n.get("on_cancel") or [], nid + "_cancel")
        self.emit("const MenuData node_%s = { %s, %s, %d, %d, %d, %d, %s, %s, %s, %s, %s, %s, %d };" % (
            nid, self.ptr(n["font"]), self.text(n.get("title") or None), lay["title_x"], lay["title_y"],
            len(lay["options"]), 1 if n.get("box") else 0, opts, self.ptr(n["cursor"]), self.box(n.get("box")),
            cancel, self.node_enum(snd.get("move")), self.node_enum(snd.get("select")), n.get("upgrades", 0)))

    def E_upgrade(self, nid, n):
        cat = n["category"]
        descs = []
        for d in n["descriptions"]:
            wrapped, _ = C.wrap_text(d, C.UPGRADE_TEXT_W)
            descs.append(cstr("\n".join(wrapped)))
        ds = self.sym(nid + "_desc")
        self.emit("static const char *const %s[] = { %s };" % (ds, ", ".join(descs)))
        reqs = n.get("requires") or []
        rs = "NULL"
        if reqs:
            items = []
            for r in reqs:
                lv = r["level"]
                if lv == "max":
                    lv = self.p.nodes[r["upgrade"]].get("max_level", 1)
                items.append("{ %s, %d, 0 }" % (self.node_enum(r["upgrade"]), lv))
            rs = self.sym(nid + "_reqs")
            self.emit("static const UpgradeReq %s[] = { %s };" % (rs, ", ".join(items)))
        on_pick = self.actions(n.get("on_pick") or [], nid + "_pick")
        self.emit("const UpgradeData node_%s = { UPG_%s, %d, %d, %d, %s, %s, %s, %s, %s, %s, %s };" % (
            nid, up(cat), 255 if cat == "bonus" else n.get("max_level", 1), len(reqs), len(descs),
            self.var_enum(n.get("var")), self.node_enum(n.get("replaces")), cstr(n["title"]),
            self.ptr(n.get("icon")), ds, rs, on_pick))

    def E_dialog(self, nid, n):
        lines = []
        for ln in n["lines"]:
            lay = C.dialog_layout(n["box"], ln)
            wrapped, _ = C.wrap_text(ln["text"], lay["text_w"])
            lines.append("{ %s, %s, %s, %d, %d, %d, %d, %d, %d }" % (
                cstr(ln.get("speaker") or None), self.ptr(ln.get("portrait")), cstr("\n".join(wrapped)),
                lay["speaker_x"], lay["speaker_y"], lay["portrait_x"], lay["portrait_y"],
                lay["text_x"], lay["text_y"]))
        ls = self.sym(nid + "_lines")
        self.emit("static const DialogLine %s[] = {\n    %s\n};" % (ls, ",\n    ".join(lines)))
        choices = n.get("choices") or []
        cs = "NULL"
        if choices:
            lay = C.dialog_layout(n["box"], {})
            pos = [(lay["inner_x"] + 1, lay["inner_y"] + i) for i in range(len(choices))]
            cs = self.options(choices, pos, nid + "_choice")
        end = self.actions(n.get("on_end") or [], nid + "_end")
        self.emit("const DialogData node_%s = { %s, %s, %d, %d, %d, %s, %s, %s };" % (
            nid, self.ptr(n["font"]), self.box(n["box"]), len(lines), len(choices),
            n.get("ticks_per_char", 1), ls, cs, end))

    def E_scene(self, nid, n):
        insts = []
        index = {}
        for i, inst in enumerate(n.get("instances", [])):
            index[inst["id"]] = i
            obj = inst["object"]
            t = self.p.type_of(obj)
            onode = self.p.nodes[obj]
            kind = {"tilemap": "INST_TILEMAP", "hud": "INST_HUD", "menu": "INST_MENU",
                    "dialog": "INST_DIALOG", "particle": "INST_PARTICLE"}.get(t, "INST_ACTOR")
            lsym, lcount = "NULL", 0
            if kind == "INST_ACTOR":
                if inst.get("overrides"):
                    lsym, lcount = self.logic(onode.get("logic") or [], "%s_%s" % (nid, inst["id"]), inst["overrides"])
                elif onode.get("logic"):
                    lsym, lcount = "logic_" + obj, len(onode["logic"])
            insts.append("{ %s, %d, %s, %d, %d, &node_%s, %s }" % (
                kind, lcount, self.node_enum(obj), inst.get("x", 0), inst.get("y", 0), obj, lsym))
        s = "NULL"
        if insts:
            s = self.sym(nid + "_instances")
            self.emit("static const InstanceData %s[] = {\n    %s\n};" % (s, ",\n    ".join(insts)))
        cam = n.get("camera") or {}
        follow = index.get(cam.get("follow"), -1)
        on_start = self.actions(n.get("on_start") or [], nid + "_start")
        hooks = self.hooks(nid, n, "void %s(void);")
        self.emit("const SceneData node_%s = { SCENE_%s, %d, %d, %s, 0x%04X, %s, %d, %d, %s, %s, %s, %s };" % (
            nid, up(n["type"]), len(insts), follow,
            "CAM_BOUNDS_NONE" if cam.get("bounds") == "none" else "CAM_BOUNDS_MAP",
            C.color_to_bgr555(n.get("backdrop", "#000000")), self.node_enum(n.get("music")),
            cam.get("x", 0), cam.get("y", 0), s, on_start, hooks[0], hooks[1]))


# Behavior param node types that become typed pointers (others become node indexes).
PARAM_NODE_PTR = {"dialog": "DialogData", "particle": "ParticleData", "sfx": "SfxData",
                  "music": "MusicData", "menu": "MenuData", "icon": "IconData"}

C_TYPES = {"int": "s32", "fixed": "fixed", "bool": "u8", "ticks": "s32", "button": "u16",
           "var": "s16", "actions": "ActionList", "points": "PointList", "choice": "u8",
           "string": "const char *"}

STRUCT_OF = {"palette": "PaletteData", "sprite": "SpriteData", "tileset": "TilesetData",
             "tilemap": "TilemapData", "font": "FontData", "icon": "IconData", "sfx": "SfxData",
             "music": "MusicData", "animation": "AnimationData", "particle": "ParticleData",
             "body": "BodyData", "hud": "HudData", "menu": "MenuData", "dialog": "DialogData",
             "upgrade": "UpgradeData"}
for _t in C.ACTOR_TYPES:
    STRUCT_OF[_t] = "ActorData"


def gen_node_ids(p):
    vars_ = p.game.get("variables", [])
    out = [HEADER, "#ifndef NODE_IDS_H\n#define NODE_IDS_H\n"]

    def enum(name, items, count=None):
        body = "\n".join("    %s," % i for i in items)
        if count:
            body += "\n    %s" % count
        out.append("// %s\nenum {\n%s\n};\n" % (name, body))

    enum("Every node (index into g_nodes)", ["NODE_%s" % up(e["id"]) for e in p.index], "NODE_COUNT")
    enum("Game variables (nodes.json game.variables)", ["VAR_%s" % up(v["name"]) for v in vars_], "VAR_COUNT")
    out.append("#define VAR_ARRAY_SIZE %d\n" % max(1, len(vars_)))
    enum("Node types", ["NT_SCENE"] + ["NT_%s" % up(t) for t in C.OBJECT_TYPES], "NT_COUNT")
    enum("Scene types", ["SCENE_%s" % up(t) for t in C.SCENE_TYPES])
    enum("Collision categories (bit = 1 << CAT_*)", ["CAT_%s" % up(c) for c in C.CATEGORIES], "CAT_COUNT")
    enum("Body animation slots", ["ANIM_%s" % up(s) for s in C.ANIM_SLOTS], "ANIM_SLOT_COUNT")
    enum("Actor sound events", ["SND_%s" % up(s) for s in C.SOUND_EVENTS], "SND_COUNT")
    enum("PSG channels", ["CH_%s" % up(c) for c in C.CHANNELS])
    enum("Actions (catalog/actions.json)", ["ACT_%s" % up(a) for a in p.actions], "ACT_COUNT")
    ops = p.actions.get("if_var", {}).get("params", {}).get("op", {}).get("options", [])
    names = {"==": "EQ", "!=": "NE", "<": "LT", "<=": "LE", ">": "GT", ">=": "GE"}
    enum("if_var comparisons", ["CMP_%s" % names[o] for o in ops])
    enum("Behaviors (catalog/behaviors.json)", ["BHV_%s" % up(b) for b in p.behaviors], "BHV_COUNT")
    out.append("#define BHV_ARRAY_SIZE %d\n" % max(1, len(p.behaviors)))
    out.append("#define GAME_SAVE %d\n" % (1 if p.game.get("save") else 0))
    out.append("#endif\n")
    return "\n".join(out)


def gen_behavior_params(p):
    out = [HEADER, "#ifndef BEHAVIOR_PARAMS_H\n#define BEHAVIOR_PARAMS_H\n",
           '#include "engine/data.h"\n']
    for b, spec in p.behaviors.items():
        fields = []
        for pname, pdef in spec.get("params", {}).items():
            t = pdef["type"]
            if t.startswith("node:"):
                nt = t[5:]
                ctype = "const %s *" % PARAM_NODE_PTR[nt] if nt in PARAM_NODE_PTR else "s16"
            else:
                ctype = C_TYPES[t]
            sep = "" if ctype.endswith("*") else " "
            fields.append("    %s%s%s;   // %s" % (ctype, sep, pname, pdef.get("description", "")))
            if t == "choice":
                for i, opt in enumerate(pdef["options"]):
                    out.append("#define %s_%s_%s %d" % (up(b), up(pname), up(opt), i))
        if not fields:
            fields.append("    u8 unused;")
        out.append("// %s\ntypedef struct {\n%s\n} Params_%s;\n" % (spec.get("description", ""), "\n".join(fields), b))
    out.append("#endif\n")
    return "\n".join(out)


def gen_game_data(p):
    g = Gen(p)
    order = []
    # Emit in dependency-friendly order; every node is also declared extern in game_data.h.
    for e in p.index:
        order.append(e["id"])
    for nid in order:
        e = p.by_id[nid]
        n = p.nodes[nid]
        g.emit("\n// ---- %s (%s) : %s" % (nid, e["type"], n.get("name", "").replace("\n", " ")))
        if e["kind"] == "scene":
            g.E_scene(nid, n)
        elif e["type"] in C.ACTOR_TYPES:
            g.E_actor(nid, n)
        else:
            getattr(g, "E_" + e["type"])(nid, n)
    # node table, game settings, variables, note tables
    rows = []
    for e in p.index:
        nt = "NT_SCENE" if e["kind"] == "scene" else "NT_%s" % up(e["type"])
        rows.append("    { %s, &node_%s, %s }," % (nt, e["id"], cstr(e["id"])))
    g.emit("\nconst NodeEntry g_nodes[NODE_COUNT] = {\n%s\n};" % "\n".join(rows))
    game = p.game
    g.emit("const GameData g_game = { %s, %s, %d, %d, %d };" % (
        cstr(game["title"]), g.node_enum(game["start_scene"]), 1 if game.get("save") else 0,
        fx(game.get("gravity", 0.25)), fx(game.get("max_fall_speed", 4))))
    inits = [int(v["initial"]) for v in game.get("variables", [])] or [0]
    g.emit("const s32 g_var_initial[VAR_ARRAY_SIZE] = { %s };" % ", ".join(str(v) for v in inits))
    keep = [1 if v.get("persistent") else 0 for v in game.get("variables", [])] or [0]
    g.emit("const u8 g_var_persistent[VAR_ARRAY_SIZE] = { %s };" % ", ".join(str(v) for v in keep))
    sq, wv = [], []
    for note in range(128):
        f = 440.0 * math.pow(2, (note - 69) / 12.0)
        sq.append(max(0, min(2047, int(round(2048 - 131072 / f)))))
        wv.append(max(0, min(2047, int(round(2048 - 65536 / f)))))
    g.emit("const u16 g_square_rate[128] = {\n%s\n};" % int_array(sq, 16))
    g.emit("const u16 g_wave_rate[128] = {\n%s\n};" % int_array(wv, 16))

    head = [HEADER, '#include "game_data.h"\n#include "behavior_params.h"\n']
    head.extend(sorted(g.extern_fns))
    c_src = "\n".join(head) + "\n" + "\n".join(g.out) + "\n"

    h = [HEADER, "#ifndef GAME_DATA_H\n#define GAME_DATA_H\n", '#include "engine/data.h"\n']
    for e in p.index:
        st = "SceneData" if e["kind"] == "scene" else STRUCT_OF[e["type"]]
        h.append("extern const %s node_%s;" % (st, e["id"]))
        if e["kind"] == "object" and e["type"] in C.ACTOR_TYPES and p.nodes[e["id"]].get("logic"):
            h.append("extern const LogicEntry logic_%s[];" % e["id"])
    h.append("\n#endif\n")
    return "\n".join(h), c_src


def gen_behaviors_table(p):
    out = [HEADER, '#include "engine/data.h"\n']
    rows = []
    for b in p.behaviors:
        path = C.behavior_source(b)
        src = open(path, "r", encoding="utf-8").read() if path else ""
        fns = []
        for hook, proto in (("init", "void bhv_%s_init(struct Actor *self, const void *params);"),
                            ("update", "void bhv_%s_update(struct Actor *self, const void *params);"),
                            ("on_touch", "void bhv_%s_on_touch(struct Actor *self, struct Actor *other, const void *params);")):
            name = "bhv_%s_%s" % (b, hook)
            if re.search(r"\b%s\s*\(" % name, src):
                out.append(proto % b)
                fns.append(name)
            else:
                fns.append("NULL")
        rows.append("    [BHV_%s] = { %s }," % (up(b), ", ".join(fns)))
    out.append("\nconst BehaviorDef g_behaviors[BHV_ARRAY_SIZE] = {\n%s\n};\n" % "\n".join(rows))
    return "\n".join(out)


def write_if_changed(path, text):
    try:
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == text:
                return False
    except OSError:
        pass
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return True


def generate(p=None):
    """Write every generated file. Assumes validation passed. Returns list of changed files."""
    p = p or C.load_project()
    os.makedirs(C.GEN_DIR, exist_ok=True)
    gh, gc = gen_game_data(p)
    files = {
        "node_ids.h": gen_node_ids(p),
        "behavior_params.h": gen_behavior_params(p),
        "game_data.h": gh,
        "game_data.c": gc,
        "behaviors_table.c": gen_behaviors_table(p),
    }
    changed = []
    for name, text in files.items():
        if write_if_changed(os.path.join(C.GEN_DIR, name), text):
            changed.append(name)
    keep = set(files)
    for fn in os.listdir(C.GEN_DIR):
        if fn not in keep:
            os.remove(os.path.join(C.GEN_DIR, fn))
    return changed


def main():
    C.setup_console()
    import validate
    r = validate.validate()
    if not r.ok:
        for e in r.errors:
            print("  ERROR    " + e)
        print("✖ Codegen skipped: fix the validation errors first.")
        return 1
    changed = generate()
    print("✔ Codegen done (%s)." % (", ".join(changed) + " updated" if changed else "nothing changed"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
